import clickhouse from '@/lib/clickhouse';
import { FIELD_LENGTH } from '@/lib/constants';
import { uuid } from '@/lib/crypto';
import { CLICKHOUSE, PRISMA, runQuery } from '@/lib/db';
import { truncateString } from '@/lib/format';
import prisma from '@/lib/prisma';

// Provider for revenue generated by tracker custom events (default).
export const REVENUE_PROVIDER_WEB = 'web';

// UUID used for unattributed external revenue in ClickHouse (no nullable keys).
export const EMPTY_UUID = '00000000-0000-0000-0000-000000000000';

export interface SaveRevenueArgs {
  websiteId: string;
  sessionId?: string;
  eventId?: string;
  eventName: string;
  provider?: string;
  providerId?: string;
  currency: string;
  revenue: number;
  createdAt: Date;
}

export async function saveRevenue(data: SaveRevenueArgs) {
  return runQuery({
    [PRISMA]: () => relationalQuery(data),
    [CLICKHOUSE]: () => clickhouseQuery(data),
  });
}

async function relationalQuery(data: SaveRevenueArgs) {
  const {
    websiteId,
    sessionId,
    eventId,
    eventName,
    provider = REVENUE_PROVIDER_WEB,
    providerId,
    currency,
    revenue,
    createdAt,
  } = data;

  const values = {
    websiteId,
    sessionId: sessionId ?? null,
    eventId: eventId ?? null,
    eventName: truncateString(eventName, FIELD_LENGTH.eventName),
    provider,
    providerId,
    currency: truncateString(currency, FIELD_LENGTH.currency),
    revenue,
    createdAt,
  };

  // External payments carry a provider transaction id; webhook deliveries are
  // retried by all providers, so upsert on (websiteId, provider, providerId).
  if (providerId) {
    return prisma.client.revenue.upsert({
      where: {
        websiteId_provider_providerId: { websiteId, provider, providerId },
      },
      create: { id: uuid(), ...values },
      update: { revenue, currency: values.currency, sessionId: values.sessionId },
    });
  }

  return prisma.client.revenue.create({
    data: { id: uuid(), ...values },
  });
}

async function clickhouseQuery(data: SaveRevenueArgs) {
  const {
    websiteId,
    sessionId,
    eventId,
    eventName,
    provider = REVENUE_PROVIDER_WEB,
    providerId,
    currency,
    revenue,
    createdAt,
  } = data;

  const { insert, getUTCString } = clickhouse;

  // Tracker-originated revenue reaches website_revenue through the
  // website_revenue_mv materialized view; this direct insert path is only for
  // external provider payments (webhooks / Payment API).
  if (provider === REVENUE_PROVIDER_WEB) {
    return;
  }

  await insert('website_revenue', [
    {
      website_id: websiteId,
      session_id: sessionId ?? EMPTY_UUID,
      event_id: eventId ?? EMPTY_UUID,
      event_name: truncateString(eventName, FIELD_LENGTH.eventName),
      provider,
      provider_id: providerId ?? '',
      currency: truncateString(currency, FIELD_LENGTH.currency),
      revenue,
      created_at: getUTCString(createdAt),
    },
  ]);
}
